# Generated by Django 2.2.6 on 2020-06-28 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20200628_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostDate',
            field=models.DateField(auto_created=True, default=datetime.datetime(2020, 6, 28, 18, 38, 30, 961986, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
