# Generated by Django 2.2.6 on 2020-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20200629_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostDate',
            field=models.DateField(auto_now=True),
        ),
    ]
