# Generated by Django 2.2.6 on 2020-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20200629_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
