# Generated by Django 2.2.6 on 2020-06-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200629_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='PostDate',
            new_name='created_at',
        ),
    ]
